# Generated by Django 5.0.1 on 2024-02-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amats',
            fields=[
                ('amata_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nosaukums', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Darbinieki',
            fields=[
                ('darb_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vards', models.CharField(max_length=15)),
                ('uzvards', models.CharField(max_length=25)),
                ('personas_kods', models.CharField(max_length=12)),
                ('talrunis', models.CharField(max_length=8)),
                ('dz_datums', models.DateField()),
                ('uzsak_datums', models.DateField()),
                ('prasmes', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=20)),
                ('parole', models.CharField(max_length=25)),
                ('menedzeris', models.BooleanField()),
                ('amata_ID',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.amats')),
            ],
        ),
        migrations.CreateModel(
            name='Pakalpojums',
            fields=[
                ('pak_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('r_numurs', models.CharField(max_length=7, unique=True)),
                ('k_parole', models.CharField(max_length=4)),
                ('nosaukums', models.CharField(max_length=50)),
                ('klients', models.CharField(max_length=50)),
                ('k_talrunis', models.CharField(max_length=8)),
                ('k_epasts', models.EmailField(max_length=50)),
                ('datums', models.DateField()),
                ('laiks', models.TimeField()),
                ('vieta', models.CharField(max_length=40)),
                ('sit_aprakts', models.TextField(max_length=300)),
                ('status', models.BooleanField(null=True)),
                ('darb_apraksts', models.TextField(max_length=300)),
                ('darb_kval', models.SmallIntegerField()),
                ('dar_atrums', models.SmallIntegerField()),
                ('apkalposanas_lim', models.SmallIntegerField()),
                ('ats_apraksts', models.TextField(max_length=150)),
                ('darb_ID',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.darbinieki')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
