# Generated by Django 5.0.1 on 2024-02-10 13:11

import myapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_amats_darbinieki_pakalpojums_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbinieki',
            name='prasmes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='k_parole',
            field=models.CharField(default=myapp.models.generate_random_code, max_length=4),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='r_numurs',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
