# Generated by Django 5.0.1 on 2024-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pakalpojums_apkalposanas_lim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbinieki',
            name='menedzeris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='apkalposanas_lim',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='dar_atrums',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='darb_kval',
            field=models.SmallIntegerField(),
        ),
    ]
