# Generated by Django 5.0.3 on 2024-03-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_darbinieki_epasts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darbinieki',
            name='amata_ID',
        ),
        migrations.RemoveField(
            model_name='darbinieki',
            name='personas_kods',
        ),
    ]
