# Generated by Django 5.0.3 on 2024-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_darbinieki_amata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darbinieki',
            name='montesana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darbinieki',
            name='programm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darbinieki',
            name='tehmont',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darbinieki',
            name='tehnika',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darbinieki',
            name='vaditajs',
            field=models.BooleanField(default=False),
        ),
    ]
