# Generated by Django 5.0.3 on 2024-03-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_darbinieki_montesana_darbinieki_programm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PakTip',
            fields=[
                ('paktip_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nosaukums', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='statuss',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='paktip_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paktip'),
        ),
    ]
