# Generated by Django 5.0.3 on 2024-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_darbinieki_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakalpojums',
            name='diagnostika',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='komplektacija',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='konts',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='nobeig_datums',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pakalpojums',
            name='serija_nr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
