# Generated by Django 5.0.3 on 2024-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pakalpojums_diagnostika_pakalpojums_komplektacija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakalpojums',
            name='pan_datums',
            field=models.DateField(null=True),
        ),
    ]
