# Generated by Django 5.0.1 on 2024-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_pakalpojums_pan_datums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakalpojums',
            name='diagnostika',
            field=models.TextField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='k_epasts',
            field=models.EmailField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='komplektacija',
            field=models.TextField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='konts',
            field=models.TextField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='serija_nr',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='vieta',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
