# Generated by Django 5.0.1 on 2024-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_pakalpojums_diagnostika_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakalpojums',
            name='diagnostika',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='k_epasts',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='komplektacija',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='konts',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='laiks',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='nobeig_datums',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='serija_nr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='vieta',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
