# Generated by Django 5.0.4 on 2024-04-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_pakalpojums_diagnostika_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakalpojums',
            name='konts',
        ),
    ]
