# Generated by Django 5.0.1 on 2024-04-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_pakalpojums_konts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakalpojums',
            name='nobraukums',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PakInfo',
            fields=[
                ('pak_info_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('datums', models.DateField()),
                ('darb_apraksts', models.TextField(default='0', max_length=300)),
                ('pak_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pakalpojums')),
            ],
        ),
    ]
