# Generated by Django 5.0.1 on 2024-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_pakalpojums_nobraukums_pakinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakalpojums',
            name='p_laiks',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
