# Generated by Django 5.0.1 on 2024-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_pakalpojums_p_laiks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakalpojums',
            name='auto',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
