# Generated by Django 5.0.1 on 2024-02-10 13:33

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_darbinieki_prasmes_alter_pakalpojums_k_parole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakalpojums',
            name='apkalposanas_lim',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='dar_atrums',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='darb_kval',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='k_parole',
            field=models.CharField(default=myapp.models.generate_random_code, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='r_numurs',
            field=models.CharField(default=myapp.models.generate_unique_seven_digit_code, editable=False, max_length=7),
        ),
    ]
