# Generated by Django 5.0.1 on 2024-02-10 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pakalpojums_apkalposanas_lim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakalpojums',
            name='apkalposanas_lim',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='dar_atrums',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pakalpojums',
            name='darb_kval',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
